### ISSUE TITLE
Expand expression language scope for PutMarkLogic's dynamic properties

### ISSUE THREAD

**Issue by brent-hartwig** [marklogic-community/marklogic-nifi-incubator#48]
Hello, 

Please consider enabling us to incorporate the values of flowfile attributes in the values of PutMarkLogic's dynamic properties.

Here's the Slack post that led to this RFE:

> Anyone know how to set the data hub flow name on the fly?  If I'm understanding correctly, all dynamic property values for the PutMarkLogic processor have an expression language scope of 'variable registry only', which omits flowfile atts.  Overall, we're seeing the potential for fewer NiFi flows to support many entities by monitoring different sub-dirs of an S3 bucket, deriving the entity name from the path, and (if able to figure it out) invoking the corresponding data flow.

**Comment by brent-hartwig** [comment]
See also https://github.com/marklogic-community/marklogic-nifi-incubator/issues/49

**Comment by missyglosenger** [comment]
We would find this very helpful too, we would like to be able to use flowfile attributes for server transforms in the PutMarkLogic processor

**Comment by rjrudin** [comment]
There are multiple closed tickets in marklogic/nifi for this. They're closed because this isn't possible for transform parameters, as the ServerTransform is at the WriteBatcher level, not at the batch or document level. So closing this as well (note that "meta" and "property" dynamic properties are evaluated against flowfiles since document metadata and document properties are of course at the document level).
