### ISSUE TITLE
putMarkLogic process changing value of attribute to a constant of -9223372036836040000

### ISSUE THREAD

**Issue by marams** [marklogic-community/marklogic-nifi-incubator#64]
putMarkLogic process is defaulting value to -9223372036836040000 when the values is -92233720368360XXXXX , this is true for all the values that are -92233720368360XXXXX. 

In my flow process I am picking up value from a file and writing to MarkLogic, in the queue before putMarkLogic process  I can see that the value is showing up correctly, but when it writes to MarkLogic the value is showing up a constant of -9223372036836040000
<img width="253" alt="WrongValueInML" src="https://user-images.githubusercontent.com/634168/72105478-9d921c80-32fb-11ea-82c7-c0dee493381f.PNG">
<img width="258" alt="CorrectValueinQueueBeforePutML" src="https://user-images.githubusercontent.com/634168/72105493-a2ef6700-32fb-11ea-978f-485cb53d6243.PNG">
<img width="245" alt="CorrectValueinQueueBeforePutML-02" src="https://user-images.githubusercontent.com/634168/72105494-a2ef6700-32fb-11ea-9ace-6e181831b5be.PNG">

 .

Any workaround / help is highly appreciated.

**Comment by sjiang99** [comment]
In JavaScript, the [Number type is a double-precision 64-bit binary format IEEE 754 value](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Number_type) (numbers between -(2^53 − 1) and 2^53 − 1). You can check the "safe" integer range. Type "Number.MIN_SAFE_INTEGER" in Query Console produces a result of "-9007199254740991", which is "smaller" than -9223372036836040000. Nothing to change in the process. My guess is your used Java Long to generate that number, which has a different min/max range.
Couple of thoughts for your fix:
1. Change the id generator so that numbers fall within the safe range, or
2. Change the id type to string by double-quoting it
