### ISSUE TITLE
PutMarkLogicRecord: NullPointerException thrown by an onBatchSuccess listener

### ISSUE THREAD

**Issue by hanshuebner** [marklogic-community/marklogic-nifi-incubator#92]
With the 1.9.1.4-incubator bundle and NiFi (both 1.11.4 and 1.12.1), we see a lot of error messages like the following in our logs:
```
2020-10-09 08:36:18,594 ERROR [pool-27-thread-2] c.m.c.datamovement.impl.WriteBatcherImpl Exception thrown by an onBatchSuccess listener
java.lang.NullPointerException: null
	at org.apache.nifi.marklogic.processor.PutMarkLogic.lambda$0(PutMarkLogic.java:287)
	at com.marklogic.client.datamovement.impl.WriteBatcherImpl.sendSuccessToListeners(WriteBatcherImpl.java:628)
	at com.marklogic.client.datamovement.impl.WriteBatcherImpl.lambda$newBatchWriteSet$1(WriteBatcherImpl.java:425)
	at com.marklogic.client.datamovement.impl.WriteBatcherImpl$BatchWriter.run(WriteBatcherImpl.java:1102)
```
I had a look at the code and found that the UUID of the flow file in the `writeBatch` event is not found in the `uriFlowFileMap` (https://github.com/marklogic-community/marklogic-nifi-incubator/blob/ml-release/nifi-nar-bundles/nifi-marklogic-bundle/nifi-marklogic-processors/src/main/java/org/apache/nifi/marklogic/processor/PutMarkLogic.java#L285).

Any idea how to fix this would be greatly appreciated!

**Comment by rjrudin** [comment]
@hanshuebner We are preparing a 1.9.1.5 release of the supported marklogic/nifi project. While we're focusing on Apache NiFi 1.9.1 still (we hope to have releases based on 1.12 in the near future), I've done some basic testing on 1.12.1 and I have not been able to reproduce this issue. 

Line 287 is throwing the error, which is the second line in this blurb:

```
String uriList = Stream.of(writeBatch.getItems()).map((item) -> {
  return item.getTargetUri();
```

The 1.9.1.5 release uses ML Java Client 5.3.2 instead of 4.x, and I am wondering if the NPE is due to a now-fixed bug in Java Client 4.x that allowed for null objects to be present in the writeBatch.getItems() array. That is the only way I can see an NPE occurring on line 287.

You mentioned 285, which is this:

```
ProcessSession session = getFlowFileInfoForWriteEvent(writeBatch.getItems()[0]).session;
```

But if getFlowFileInfo did return null, then the stacktrace would report line 285, not line 287. So I don't think that line is the culprit. 

If you are able to test 1.9.1.5 once it's released and reproduce this error, please open a ticket in the marklogic/nifi project.

**Comment by hanshuebner** [comment]
I'm closing this report for now and will reopen a new ticket if I see the problem again.

**Comment by gareth-rogers-healx** [comment]
I believe we are seeing the same, or similar, error with `1.9.1.5` although we do not get an extensive stack trace. This is all I can see in the cloud watch NiFi logs:

`2021-04-30 12:34:58,076 ERROR [Timer-Driven Process Thread-3] c.m.c.datamovement.impl.WriteBatcherImpl Exception thrown by an onBatchSuccess listener`

and

`java.lang.NullPointerException: null`

**Comment by rjrudin** [comment]
@gareth-rogers-healx If it's an issue with the marklogic-nifi release, please open a ticket in that project, as it's supported. Please include steps on how to reproduce.
